repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 5ba58aca0bd5bc7c0e1c0fc45af2e88d6a2bde83  # frozen: v0.14.10
    hooks:
      - id: ruff-check
        args:
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
        exclude: (docs/conf.py)
      - id: check-json
      - id: check-yaml
      - id: debug-statements
        exclude: (tests/messages/data/)
      - id: end-of-file-fixer
        exclude: (tests/messages/data/)
      - id: name-tests-test
        args: [ '--django' ]
        exclude: (tests/messages/data/|.*(consts|utils).py)
      - id: requirements-txt-fixer
      - id: trailing-whitespace
