language: python

# Use travis docker infrastructure for greater speed
sudo: false

cache:
  directories:
  - cldr
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.6
      env:
      - CDECIMAL=m3-cdecimal
    - os: linux
      python: 2.7
    - os: linux
      python: 2.7
      env:
      - CDECIMAL=m3-cdecimal
    - os: linux
      python: pypy
    - os: linux
      python: pypy3
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
      env:
      - PYTHON_TEST_FLAGS=-bb

install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh
  - pip install --upgrade pip
  - pip install --upgrade pytest==2.8.5 pytest-cov==2.2.0 $CDECIMAL
  - pip install --editable .

script:
  - make test-cov
  - bash .ci/deploy.${TRAVIS_OS_NAME}.sh

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
